title: Miles von Herrmann
logo: "/images/linkedin_pic.jpeg"

description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/miles-von-herrmann-7b6969a7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
